//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 11 storyboards.
  struct storyboard {
    /// Storyboard `AddDataStoryboard`.
    static let addDataStoryboard = _R.storyboard.addDataStoryboard()
    /// Storyboard `AddPhotoStoryboard`.
    static let addPhotoStoryboard = _R.storyboard.addPhotoStoryboard()
    /// Storyboard `DetailedPhotoStoryboard`.
    static let detailedPhotoStoryboard = _R.storyboard.detailedPhotoStoryboard()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `MainGalleryStoryboard`.
    static let mainGalleryStoryboard = _R.storyboard.mainGalleryStoryboard()
    /// Storyboard `RootStoryboard`.
    static let rootStoryboard = _R.storyboard.rootStoryboard()
    /// Storyboard `SettingsStoryboard`.
    static let settingsStoryboard = _R.storyboard.settingsStoryboard()
    /// Storyboard `SignInStoryboard`.
    static let signInStoryboard = _R.storyboard.signInStoryboard()
    /// Storyboard `SignUp`.
    static let signUp = _R.storyboard.signUp()
    /// Storyboard `UserProfileStoryboard`.
    static let userProfileStoryboard = _R.storyboard.userProfileStoryboard()
    /// Storyboard `WelcomeStoryboard`.
    static let welcomeStoryboard = _R.storyboard.welcomeStoryboard()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "AddDataStoryboard", bundle: ...)`
    static func addDataStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.addDataStoryboard)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "AddPhotoStoryboard", bundle: ...)`
    static func addPhotoStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.addPhotoStoryboard)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "DetailedPhotoStoryboard", bundle: ...)`
    static func detailedPhotoStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.detailedPhotoStoryboard)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "MainGalleryStoryboard", bundle: ...)`
    static func mainGalleryStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.mainGalleryStoryboard)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "RootStoryboard", bundle: ...)`
    static func rootStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.rootStoryboard)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "SettingsStoryboard", bundle: ...)`
    static func settingsStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.settingsStoryboard)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "SignInStoryboard", bundle: ...)`
    static func signInStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.signInStoryboard)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "SignUp", bundle: ...)`
    static func signUp(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.signUp)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "UserProfileStoryboard", bundle: ...)`
    static func userProfileStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.userProfileStoryboard)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "WelcomeStoryboard", bundle: ...)`
    static func welcomeStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.welcomeStoryboard)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 20 images.
  struct image {
    /// Image `Bear`.
    static let bear = Rswift.ImageResource(bundle: R.hostingBundle, name: "Bear")
    /// Image `Camera`.
    static let camera = Rswift.ImageResource(bundle: R.hostingBundle, name: "Camera")
    /// Image `ErrorIcon`.
    static let errorIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "ErrorIcon")
    /// Image `Field`.
    static let field = Rswift.ImageResource(bundle: R.hostingBundle, name: "Field")
    /// Image `Flower`.
    static let flower = Rswift.ImageResource(bundle: R.hostingBundle, name: "Flower")
    /// Image `Fog`.
    static let fog = Rswift.ImageResource(bundle: R.hostingBundle, name: "Fog")
    /// Image `Forest`.
    static let forest = Rswift.ImageResource(bundle: R.hostingBundle, name: "Forest")
    /// Image `Home`.
    static let home = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home")
    /// Image `Info`.
    static let info = Rswift.ImageResource(bundle: R.hostingBundle, name: "Info")
    /// Image `Logo`.
    static let logo = Rswift.ImageResource(bundle: R.hostingBundle, name: "Logo")
    /// Image `PhotoIcon-1`.
    static let photoIcon1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "PhotoIcon-1")
    /// Image `Photo`.
    static let photo = Rswift.ImageResource(bundle: R.hostingBundle, name: "Photo")
    /// Image `User`.
    static let user = Rswift.ImageResource(bundle: R.hostingBundle, name: "User")
    /// Image `calendarIcon`.
    static let calendarIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "calendarIcon")
    /// Image `emailIcon`.
    static let emailIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "emailIcon")
    /// Image `eyeIcon`.
    static let eyeIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "eyeIcon")
    /// Image `gear`.
    static let gear = Rswift.ImageResource(bundle: R.hostingBundle, name: "gear")
    /// Image `logo1`.
    static let logo1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "logo1")
    /// Image `photoIcon`.
    static let photoIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "photoIcon")
    /// Image `userIcon`.
    static let userIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "userIcon")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Bear", bundle: ..., traitCollection: ...)`
    static func bear(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bear, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Camera", bundle: ..., traitCollection: ...)`
    static func camera(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.camera, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "ErrorIcon", bundle: ..., traitCollection: ...)`
    static func errorIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.errorIcon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Field", bundle: ..., traitCollection: ...)`
    static func field(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.field, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Flower", bundle: ..., traitCollection: ...)`
    static func flower(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.flower, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Fog", bundle: ..., traitCollection: ...)`
    static func fog(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fog, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Forest", bundle: ..., traitCollection: ...)`
    static func forest(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.forest, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Home", bundle: ..., traitCollection: ...)`
    static func home(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Info", bundle: ..., traitCollection: ...)`
    static func info(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.info, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Logo", bundle: ..., traitCollection: ...)`
    static func logo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.logo, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Photo", bundle: ..., traitCollection: ...)`
    static func photo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.photo, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "PhotoIcon-1", bundle: ..., traitCollection: ...)`
    static func photoIcon1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.photoIcon1, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "User", bundle: ..., traitCollection: ...)`
    static func user(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.user, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "calendarIcon", bundle: ..., traitCollection: ...)`
    static func calendarIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.calendarIcon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "emailIcon", bundle: ..., traitCollection: ...)`
    static func emailIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.emailIcon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "eyeIcon", bundle: ..., traitCollection: ...)`
    static func eyeIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.eyeIcon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "gear", bundle: ..., traitCollection: ...)`
    static func gear(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gear, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "logo1", bundle: ..., traitCollection: ...)`
    static func logo1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.logo1, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "photoIcon", bundle: ..., traitCollection: ...)`
    static func photoIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.photoIcon, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "userIcon", bundle: ..., traitCollection: ...)`
    static func userIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.userIcon, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.reuseIdentifier` struct is generated, and contains static references to 2 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `ImageCell`.
    static let imageCell: Rswift.ReuseIdentifier<GalleryPhotoCell> = Rswift.ReuseIdentifier(identifier: "ImageCell")
    /// Reuse identifier `PhotoViewCell`.
    static let photoViewCell: Rswift.ReuseIdentifier<PhotoCell> = Rswift.ReuseIdentifier(identifier: "PhotoViewCell")

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    /// This `R.string.responseHandlers` struct is generated, and contains static references to 9 localization keys.
    struct responseHandlers {
      /// Value: *! You have not logged in for a long time, please log in again.
      static let youHaveNotLoggedInForAlongTimePleaseLogInAgain = Rswift.StringResource(key: "YouHaveNotLoggedInForAlongTimePleaseLogInAgain", tableName: "ResponseHandlers", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 404 не найдено  
      static let notFound = Rswift.StringResource(key: "NotFound", tableName: "ResponseHandlers", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Application Error.
      static let appError = Rswift.StringResource(key: "AppError", tableName: "ResponseHandlers", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Incorrect code, try again.
      static let incorrectCodeTryAgain = Rswift.StringResource(key: "IncorrectCodeTryAgain", tableName: "ResponseHandlers", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Incorrect username or password
      static let incorrectUsernameOrPassword = Rswift.StringResource(key: "IncorrectUsernameOrPassword", tableName: "ResponseHandlers", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: No username or password.
      static let noUsernameOrPassword = Rswift.StringResource(key: "NoUsernameOrPassword", tableName: "ResponseHandlers", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Requesting a code can only be done once every 2 minutes. Please try again later.
      static let requestingCodeCanOnlyBeDoneOnceEvery2MinutesPleaseTryAgainLater = Rswift.StringResource(key: "RequestingCodeCanOnlyBeDoneOnceEvery2MinutesPleaseTryAgainLater", tableName: "ResponseHandlers", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: The API client is not configured correctly, please contact customer support.
      static let apiClientIsNotConfiguredCorrectlyPleaseContactTechnicalSupport = Rswift.StringResource(key: "ApiClientIsNotConfiguredCorrectlyPleaseContactTechnicalSupport", tableName: "ResponseHandlers", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: The user has not been activated. Please contact support.
      static let userNotActivatedYouCanWithSupport = Rswift.StringResource(key: "UserNotActivatedYouCanWithSupport", tableName: "ResponseHandlers", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: *! You have not logged in for a long time, please log in again.
      static func youHaveNotLoggedInForAlongTimePleaseLogInAgain(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("YouHaveNotLoggedInForAlongTimePleaseLogInAgain", tableName: "ResponseHandlers", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ResponseHandlers", preferredLanguages: preferredLanguages) else {
          return "YouHaveNotLoggedInForAlongTimePleaseLogInAgain"
        }

        return NSLocalizedString("YouHaveNotLoggedInForAlongTimePleaseLogInAgain", tableName: "ResponseHandlers", bundle: bundle, comment: "")
      }

      /// Value: 404 не найдено  
      static func notFound(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("NotFound", tableName: "ResponseHandlers", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ResponseHandlers", preferredLanguages: preferredLanguages) else {
          return "NotFound"
        }

        return NSLocalizedString("NotFound", tableName: "ResponseHandlers", bundle: bundle, comment: "")
      }

      /// Value: Application Error.
      static func appError(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("AppError", tableName: "ResponseHandlers", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ResponseHandlers", preferredLanguages: preferredLanguages) else {
          return "AppError"
        }

        return NSLocalizedString("AppError", tableName: "ResponseHandlers", bundle: bundle, comment: "")
      }

      /// Value: Incorrect code, try again.
      static func incorrectCodeTryAgain(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("IncorrectCodeTryAgain", tableName: "ResponseHandlers", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ResponseHandlers", preferredLanguages: preferredLanguages) else {
          return "IncorrectCodeTryAgain"
        }

        return NSLocalizedString("IncorrectCodeTryAgain", tableName: "ResponseHandlers", bundle: bundle, comment: "")
      }

      /// Value: Incorrect username or password
      static func incorrectUsernameOrPassword(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("IncorrectUsernameOrPassword", tableName: "ResponseHandlers", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ResponseHandlers", preferredLanguages: preferredLanguages) else {
          return "IncorrectUsernameOrPassword"
        }

        return NSLocalizedString("IncorrectUsernameOrPassword", tableName: "ResponseHandlers", bundle: bundle, comment: "")
      }

      /// Value: No username or password.
      static func noUsernameOrPassword(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("NoUsernameOrPassword", tableName: "ResponseHandlers", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ResponseHandlers", preferredLanguages: preferredLanguages) else {
          return "NoUsernameOrPassword"
        }

        return NSLocalizedString("NoUsernameOrPassword", tableName: "ResponseHandlers", bundle: bundle, comment: "")
      }

      /// Value: Requesting a code can only be done once every 2 minutes. Please try again later.
      static func requestingCodeCanOnlyBeDoneOnceEvery2MinutesPleaseTryAgainLater(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("RequestingCodeCanOnlyBeDoneOnceEvery2MinutesPleaseTryAgainLater", tableName: "ResponseHandlers", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ResponseHandlers", preferredLanguages: preferredLanguages) else {
          return "RequestingCodeCanOnlyBeDoneOnceEvery2MinutesPleaseTryAgainLater"
        }

        return NSLocalizedString("RequestingCodeCanOnlyBeDoneOnceEvery2MinutesPleaseTryAgainLater", tableName: "ResponseHandlers", bundle: bundle, comment: "")
      }

      /// Value: The API client is not configured correctly, please contact customer support.
      static func apiClientIsNotConfiguredCorrectlyPleaseContactTechnicalSupport(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("ApiClientIsNotConfiguredCorrectlyPleaseContactTechnicalSupport", tableName: "ResponseHandlers", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ResponseHandlers", preferredLanguages: preferredLanguages) else {
          return "ApiClientIsNotConfiguredCorrectlyPleaseContactTechnicalSupport"
        }

        return NSLocalizedString("ApiClientIsNotConfiguredCorrectlyPleaseContactTechnicalSupport", tableName: "ResponseHandlers", bundle: bundle, comment: "")
      }

      /// Value: The user has not been activated. Please contact support.
      static func userNotActivatedYouCanWithSupport(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("UserNotActivatedYouCanWithSupport", tableName: "ResponseHandlers", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "ResponseHandlers", preferredLanguages: preferredLanguages) else {
          return "UserNotActivatedYouCanWithSupport"
        }

        return NSLocalizedString("UserNotActivatedYouCanWithSupport", tableName: "ResponseHandlers", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.scenes` struct is generated, and contains static references to 42 localization keys.
    struct scenes {
      /// Value: %@ can contain only latin letters, numbers, punctuation marks
      static let forbiddenSymbolsForPasswordEng = Rswift.StringResource(key: "forbiddenSymbolsForPasswordEng", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: %@ cannot be empty
      static let fieldIsEmptyEng = Rswift.StringResource(key: "fieldIsEmptyEng", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: %@ couldn't be less than %@ symbols
      static let fieldIsTooShortEng = Rswift.StringResource(key: "fieldIsTooShortEng", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: %@ не может быть более %@ символов
      static let fieldIsTooLong = Rswift.StringResource(key: "fieldIsTooLong", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: %@ не может быть менее %@ символов
      static let fieldIsTooShort = Rswift.StringResource(key: "fieldIsTooShort", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: '%@' должно содержать %@ символов
      static let fieldIsNoEqual = Rswift.StringResource(key: "fieldIsNoEqual", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: '%@' может содержать только буквы, пробел, дефис
      static let forbiddenSymbolsForText = Rswift.StringResource(key: "forbiddenSymbolsForText", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: '%@' может содержать только латинские буквы, цифры, знак подчёркивания, точку и минус
      static let forbiddenSymbolsForEmailOrUsername = Rswift.StringResource(key: "forbiddenSymbolsForEmailOrUsername", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: '%@' может содержать только латинские буквы, цифры, знаки препинания
      static let forbiddenSymbolsForPassword = Rswift.StringResource(key: "forbiddenSymbolsForPassword", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: '%@' не может быть пустым
      static let fieldIsEmpty = Rswift.StringResource(key: "fieldIsEmpty", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Account is deleted
      static let accountIsDeleted = Rswift.StringResource(key: "accountIsDeleted", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Birthday
      static let dateOfBirth = Rswift.StringResource(key: "dateOfBirth", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Confirm password
      static let confirmPassword = Rswift.StringResource(key: "confirmPassword", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: E-mail
      static let email = Rswift.StringResource(key: "email", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Error
      static let error = Rswift.StringResource(key: "error", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Name
      static let name = Rswift.StringResource(key: "name", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: OK
      static let okAction = Rswift.StringResource(key: "okAction", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Password
      static let password = Rswift.StringResource(key: "password", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Passwords are different
      static let passwordsAreDifferentEng = Rswift.StringResource(key: "passwordsAreDifferentEng", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Passwords aren't identical
      static let passwordsNotMatch = Rswift.StringResource(key: "passwordsNotMatch", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Phone number
      static let phoneNumber = Rswift.StringResource(key: "phoneNumber", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Please, check your data
      static let pleaseCheckYourData = Rswift.StringResource(key: "pleaseCheckYourData", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Publication has been moderated
      static let successInPublicationMessage = Rswift.StringResource(key: "successInPublicationMessage", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Save
      static let save = Rswift.StringResource(key: "save", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Search
      static let searchCase = Rswift.StringResource(key: "searchCase", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Sorry. Something went wrong
      static let failInPublicationMessage = Rswift.StringResource(key: "failInPublicationMessage", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Success
      static let successMessage = Rswift.StringResource(key: "SuccessMessage", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Surname
      static let surname = Rswift.StringResource(key: "surname", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: User Name
      static let username = Rswift.StringResource(key: "username", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Wrong format
      static let incorrectEng = Rswift.StringResource(key: "incorrectEng", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: You didn't fill all required fields
      static let emptyFieldsMessage = Rswift.StringResource(key: "emptyFieldsMessage", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Your data is successfully changed
      static let dataIsChanged = Rswift.StringResource(key: "dataIsChanged", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Дата еще не наступила
      static let dateStillToCome = Rswift.StringResource(key: "dateStillToCome", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Дата уже прошла
      static let dateAlreadyPast = Rswift.StringResource(key: "dateAlreadyPast", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Меньше необходимого временного интервала
      static let lessThanRequiredTimeInterval = Rswift.StringResource(key: "lessThanRequiredTimeInterval", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Название
      static let violationEntityName = Rswift.StringResource(key: "violationEntityName", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Не удалось найти идентификатор пользователя. Обновите профиль
      static let localUserIdIsNil = Rswift.StringResource(key: "localUserIdIsNil", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Не удалось получить ID пользователя
      static let remoteUserIdIsNil = Rswift.StringResource(key: "remoteUserIdIsNil", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Неверный формат
      static let incorrect = Rswift.StringResource(key: "incorrect", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Номер совпадает с текущим
      static let equalPhoneNumber = Rswift.StringResource(key: "equalPhoneNumber", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Пароли не совпадают
      static let passwordsAreDifferent = Rswift.StringResource(key: "passwordsAreDifferent", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Почта
      static let violationEntityEmail = Rswift.StringResource(key: "violationEntityEmail", tableName: "Scenes", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: %@ can contain only latin letters, numbers, punctuation marks
      static func forbiddenSymbolsForPasswordEng(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("forbiddenSymbolsForPasswordEng", tableName: "Scenes", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "forbiddenSymbolsForPasswordEng"
        }

        let format = NSLocalizedString("forbiddenSymbolsForPasswordEng", tableName: "Scenes", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// Value: %@ cannot be empty
      static func fieldIsEmptyEng(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("fieldIsEmptyEng", tableName: "Scenes", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "fieldIsEmptyEng"
        }

        let format = NSLocalizedString("fieldIsEmptyEng", tableName: "Scenes", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// Value: %@ couldn't be less than %@ symbols
      static func fieldIsTooShortEng(_ value1: String, _ value2: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("fieldIsTooShortEng", tableName: "Scenes", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1, value2)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "fieldIsTooShortEng"
        }

        let format = NSLocalizedString("fieldIsTooShortEng", tableName: "Scenes", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1, value2)
      }

      /// Value: %@ не может быть более %@ символов
      static func fieldIsTooLong(_ value1: String, _ value2: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("fieldIsTooLong", tableName: "Scenes", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1, value2)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "fieldIsTooLong"
        }

        let format = NSLocalizedString("fieldIsTooLong", tableName: "Scenes", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1, value2)
      }

      /// Value: %@ не может быть менее %@ символов
      static func fieldIsTooShort(_ value1: String, _ value2: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("fieldIsTooShort", tableName: "Scenes", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1, value2)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "fieldIsTooShort"
        }

        let format = NSLocalizedString("fieldIsTooShort", tableName: "Scenes", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1, value2)
      }

      /// Value: '%@' должно содержать %@ символов
      static func fieldIsNoEqual(_ value1: String, _ value2: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("fieldIsNoEqual", tableName: "Scenes", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1, value2)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "fieldIsNoEqual"
        }

        let format = NSLocalizedString("fieldIsNoEqual", tableName: "Scenes", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1, value2)
      }

      /// Value: '%@' может содержать только буквы, пробел, дефис
      static func forbiddenSymbolsForText(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("forbiddenSymbolsForText", tableName: "Scenes", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "forbiddenSymbolsForText"
        }

        let format = NSLocalizedString("forbiddenSymbolsForText", tableName: "Scenes", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// Value: '%@' может содержать только латинские буквы, цифры, знак подчёркивания, точку и минус
      static func forbiddenSymbolsForEmailOrUsername(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("forbiddenSymbolsForEmailOrUsername", tableName: "Scenes", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "forbiddenSymbolsForEmailOrUsername"
        }

        let format = NSLocalizedString("forbiddenSymbolsForEmailOrUsername", tableName: "Scenes", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// Value: '%@' может содержать только латинские буквы, цифры, знаки препинания
      static func forbiddenSymbolsForPassword(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("forbiddenSymbolsForPassword", tableName: "Scenes", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "forbiddenSymbolsForPassword"
        }

        let format = NSLocalizedString("forbiddenSymbolsForPassword", tableName: "Scenes", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// Value: '%@' не может быть пустым
      static func fieldIsEmpty(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("fieldIsEmpty", tableName: "Scenes", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "fieldIsEmpty"
        }

        let format = NSLocalizedString("fieldIsEmpty", tableName: "Scenes", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// Value: Account is deleted
      static func accountIsDeleted(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("accountIsDeleted", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "accountIsDeleted"
        }

        return NSLocalizedString("accountIsDeleted", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Birthday
      static func dateOfBirth(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("dateOfBirth", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "dateOfBirth"
        }

        return NSLocalizedString("dateOfBirth", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Confirm password
      static func confirmPassword(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("confirmPassword", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "confirmPassword"
        }

        return NSLocalizedString("confirmPassword", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: E-mail
      static func email(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("email", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "email"
        }

        return NSLocalizedString("email", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Error
      static func error(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("error", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "error"
        }

        return NSLocalizedString("error", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Name
      static func name(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("name", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "name"
        }

        return NSLocalizedString("name", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: OK
      static func okAction(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("okAction", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "okAction"
        }

        return NSLocalizedString("okAction", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Password
      static func password(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("password", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "password"
        }

        return NSLocalizedString("password", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Passwords are different
      static func passwordsAreDifferentEng(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("passwordsAreDifferentEng", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "passwordsAreDifferentEng"
        }

        return NSLocalizedString("passwordsAreDifferentEng", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Passwords aren't identical
      static func passwordsNotMatch(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("passwordsNotMatch", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "passwordsNotMatch"
        }

        return NSLocalizedString("passwordsNotMatch", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Phone number
      static func phoneNumber(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("phoneNumber", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "phoneNumber"
        }

        return NSLocalizedString("phoneNumber", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Please, check your data
      static func pleaseCheckYourData(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("pleaseCheckYourData", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "pleaseCheckYourData"
        }

        return NSLocalizedString("pleaseCheckYourData", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Publication has been moderated
      static func successInPublicationMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("successInPublicationMessage", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "successInPublicationMessage"
        }

        return NSLocalizedString("successInPublicationMessage", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Save
      static func save(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("save", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "save"
        }

        return NSLocalizedString("save", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Search
      static func searchCase(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("searchCase", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "searchCase"
        }

        return NSLocalizedString("searchCase", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Sorry. Something went wrong
      static func failInPublicationMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("failInPublicationMessage", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "failInPublicationMessage"
        }

        return NSLocalizedString("failInPublicationMessage", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Success
      static func successMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("SuccessMessage", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "SuccessMessage"
        }

        return NSLocalizedString("SuccessMessage", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Surname
      static func surname(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("surname", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "surname"
        }

        return NSLocalizedString("surname", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: User Name
      static func username(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("username", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "username"
        }

        return NSLocalizedString("username", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Wrong format
      static func incorrectEng(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("incorrectEng", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "incorrectEng"
        }

        return NSLocalizedString("incorrectEng", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: You didn't fill all required fields
      static func emptyFieldsMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("emptyFieldsMessage", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "emptyFieldsMessage"
        }

        return NSLocalizedString("emptyFieldsMessage", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Your data is successfully changed
      static func dataIsChanged(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("dataIsChanged", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "dataIsChanged"
        }

        return NSLocalizedString("dataIsChanged", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Дата еще не наступила
      static func dateStillToCome(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("dateStillToCome", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "dateStillToCome"
        }

        return NSLocalizedString("dateStillToCome", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Дата уже прошла
      static func dateAlreadyPast(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("dateAlreadyPast", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "dateAlreadyPast"
        }

        return NSLocalizedString("dateAlreadyPast", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Меньше необходимого временного интервала
      static func lessThanRequiredTimeInterval(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("lessThanRequiredTimeInterval", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "lessThanRequiredTimeInterval"
        }

        return NSLocalizedString("lessThanRequiredTimeInterval", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Название
      static func violationEntityName(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("violationEntityName", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "violationEntityName"
        }

        return NSLocalizedString("violationEntityName", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Не удалось найти идентификатор пользователя. Обновите профиль
      static func localUserIdIsNil(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("localUserIdIsNil", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "localUserIdIsNil"
        }

        return NSLocalizedString("localUserIdIsNil", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Не удалось получить ID пользователя
      static func remoteUserIdIsNil(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("remoteUserIdIsNil", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "remoteUserIdIsNil"
        }

        return NSLocalizedString("remoteUserIdIsNil", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Неверный формат
      static func incorrect(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("incorrect", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "incorrect"
        }

        return NSLocalizedString("incorrect", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Номер совпадает с текущим
      static func equalPhoneNumber(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("equalPhoneNumber", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "equalPhoneNumber"
        }

        return NSLocalizedString("equalPhoneNumber", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Пароли не совпадают
      static func passwordsAreDifferent(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("passwordsAreDifferent", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "passwordsAreDifferent"
        }

        return NSLocalizedString("passwordsAreDifferent", tableName: "Scenes", bundle: bundle, comment: "")
      }

      /// Value: Почта
      static func violationEntityEmail(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("violationEntityEmail", tableName: "Scenes", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Scenes", preferredLanguages: preferredLanguages) else {
          return "violationEntityEmail"
        }

        return NSLocalizedString("violationEntityEmail", tableName: "Scenes", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try addDataStoryboard.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try addPhotoStoryboard.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try detailedPhotoStoryboard.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try mainGalleryStoryboard.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try rootStoryboard.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try settingsStoryboard.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try signInStoryboard.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try signUp.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try userProfileStoryboard.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try welcomeStoryboard.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct addDataStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = AddDataViewController

      let bundle = R.hostingBundle
      let name = "AddDataStoryboard"

      static func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "photo") == nil { throw Rswift.ValidationError(description: "[R.swift] System image named 'photo' is used in storyboard 'AddDataStoryboard', but couldn't be loaded.") } }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct addPhotoStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = AddPhotoViewController

      let bundle = R.hostingBundle
      let name = "AddPhotoStoryboard"

      static func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "photo") == nil { throw Rswift.ValidationError(description: "[R.swift] System image named 'photo' is used in storyboard 'AddPhotoStoryboard', but couldn't be loaded.") } }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct detailedPhotoStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = DetailedPhotoViewController

      let bundle = R.hostingBundle
      let name = "DetailedPhotoStoryboard"

      static func validate() throws {
        if UIKit.UIImage(named: "eyeIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'eyeIcon' is used in storyboard 'DetailedPhotoStoryboard', but couldn't be loaded.") }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "photo") == nil { throw Rswift.ValidationError(description: "[R.swift] System image named 'photo' is used in storyboard 'DetailedPhotoStoryboard', but couldn't be loaded.") } }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if UIKit.UIImage(named: "logo1", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'logo1' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct mainGalleryStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = MainGalleryViewController

      let bundle = R.hostingBundle
      let name = "MainGalleryStoryboard"

      static func validate() throws {
        if UIKit.UIImage(named: "ErrorIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ErrorIcon' is used in storyboard 'MainGalleryStoryboard', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct rootStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UITabBarController

      let bundle = R.hostingBundle
      let name = "RootStoryboard"

      static func validate() throws {
        if UIKit.UIImage(named: "Home", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Home' is used in storyboard 'RootStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Photo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Photo' is used in storyboard 'RootStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "User", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'User' is used in storyboard 'RootStoryboard', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct settingsStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = SettingsViewController

      let bundle = R.hostingBundle
      let name = "SettingsStoryboard"

      static func validate() throws {
        if UIKit.UIImage(named: "PhotoIcon-1", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'PhotoIcon-1' is used in storyboard 'SettingsStoryboard', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct signInStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = SignInViewController

      let bundle = R.hostingBundle
      let name = "SignInStoryboard"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct signUp: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = SignUpViewController

      let bundle = R.hostingBundle
      let name = "SignUp"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct userProfileStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UserProfileViewController

      let bundle = R.hostingBundle
      let name = "UserProfileStoryboard"

      static func validate() throws {
        if UIKit.UIImage(named: "ErrorIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ErrorIcon' is used in storyboard 'UserProfileStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "PhotoIcon-1", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'PhotoIcon-1' is used in storyboard 'UserProfileStoryboard', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct welcomeStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController

      let bundle = R.hostingBundle
      let name = "WelcomeStoryboard"
      let welcomeId = StoryboardViewControllerResource<WelcomeController>(identifier: "welcomeId")

      func welcomeId(_: Void = ()) -> WelcomeController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: welcomeId)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "Logo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Logo' is used in storyboard 'WelcomeStoryboard', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.welcomeStoryboard().welcomeId() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'welcomeId' could not be loaded from storyboard 'WelcomeStoryboard' as 'WelcomeController'.") }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
